# Python 3.11 obrazini tanlaymiz
FROM python:3.11-slim

# Muhit o'zgaruvchilari
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PORT 8080

WORKDIR /app

# Tizim paketlarini o'rnatish
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Bog'liqliklarni o'rnatish
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Loyihani nusxalash
COPY . /app/

# Statik fayllar uchun papka yaratish va yig'ish
RUN mkdir -p /app/staticfiles
RUN python manage.py collectstatic --noinput

# Migratsiya, Superuser yaratish va Serverni yoqish
CMD python manage.py migrate && \
    python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'Admin123456!')" && \
    gunicorn school_project.wsgi:application --bind 0.0.0.0:${PORT}