# Python obrazini tanlaymiz
FROM python:3.11-slim

# Muhit o'zgaruvchilari
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Ishchi katalogni belgilaymiz
WORKDIR /app

# Tizim kutubxonalarini o'rnatish (PostgreSQL uchun kerak)
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Bog'liqliklarni o'rnatish
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Loyihani nusxalash
COPY . /app/

# Statik fayllarni yig'ish
RUN python manage.py collectstatic --noinput

# Railway porti uchun (Railway avtomatik PORT o'zgaruvchisini beradi)
EXPOSE 8000

# Serverni ishga tushirish (Migratsiyalarni ham avtomatlashtirish mumkin)
CMD python manage.py migrate && gunicorn school_project.wsgi:application --bind 0.0.0.0:${PORT:-8000}