# Generated by Django 6.0.4 on 2026-04-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='category',
            field=models.CharField(choices=[('building', 'Maktab binosi'), ('classes', 'Dars jarayoni'), ('events', 'Tadbirlar'), ('sports', 'Sport')], default='building', max_length=50),
        ),
        migrations.RemoveField(
            model_name='notablegraduate',
            name='graduating_class',
        ),
        migrations.DeleteModel(
            name='LibraryCategory',
        ),
        migrations.DeleteModel(
            name='SchoolEvent',
        ),
        migrations.DeleteModel(
            name='SchoolInfo',
        ),
        migrations.DeleteModel(
            name='SportsFacility',
        ),
        migrations.DeleteModel(
            name='SportsTeam',
        ),
        migrations.DeleteModel(
            name='UniversityStats',
        ),
        migrations.RemoveField(
            model_name='libraryitem',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='level',
            field=models.CharField(choices=[('Maktab', 'Maktab'), ('Shahar', 'Shahar'), ('Viloyat', 'Viloyat'), ('Respublika', 'Respublika'), ('Xalqaro', 'Xalqaro')], default='Maktab', max_length=50),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='library/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.CharField(choices=[('Oliy toifali', 'Oliy toifali'), ('1-toifali', '1-toifali')], max_length=100),
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
        migrations.DeleteModel(
            name='GraduatingClass',
        ),
        migrations.DeleteModel(
            name='NotableGraduate',
        ),
    ]
